(define (make-account balance password)
  (let ((incorrect-tries 0))
    (define (call-the-cops)
      "The cops have been called motherfucker!")
    (define (withdraw amount)
      (if (>= balance amount)
          (begin (set! balance (- balance amount))
                 balance)
          "Insufficient funds"))
    (define (deposit amount)
      (set! balance (+ balance amount))
      balance)
    (lambda (password-guess m)
      (if (not (eq? password-guess password))
          (lambda (x)
            (set! incorrect-tries (+ incorrect-tries 1))
            (if (> incorrect-tries 7)
                (call-the-cops)
                "Incorrect password"))
          (begin (set! incorrect-tries 0)
                 (cond ((eq? m 'withdraw) withdraw)
                       ((eq? m 'deposit) deposit)
                       (else (error "Unknown request -- MAKE-ACCOUNT"  m))))))))

(define acc (make-account 100 'secret-password))

((acc 'secret-password 'withdraw) 40)

((acc 'some-other-password 'deposit) 50)
((acc 'some-other-password 'deposit) 50)
((acc 'some-other-password 'deposit) 50)
((acc 'some-other-password 'deposit) 50)
((acc 'some-other-password 'deposit) 50)
((acc 'some-other-password 'deposit) 50)
((acc 'some-other-password 'deposit) 50)
((acc 'some-other-password 'deposit) 50)